version: '3.7'
services:

    ping:
        build: ping

    calc:
        build: calc

    soma:
        build: soma

    sub:
        build: sub

    mult:
        build: mult
        ports:
            - "5001:5001"
            - "5002:5002"
            - "5003:5003"

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - ping
           - calc
           - soma
           - sub
           - mult